---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Make sur docker systemd directory exists.
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0640

# TODO: Remove this shim once 18.09.1 or later is released.
- import_tasks: docker-1809-shim.yml
  when: ansible_service_mgr == 'systemd'

- name: Make sur docker conf director exists.
  file:
    path: /etc/docker
    state: directory
    mode: 0600
    owner: root
    group: root

- name: Ensure Docker configuration is present.
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: docker
    mode: 0640
  with_items:
    - { src: 'daemon.json.j2', dest: '/etc/docker/daemon.json', when: true }
    - { src: 'docker.conf', dest: '/etc/systemd/system/docker.service.d/docker.conf', when: true }
    - { src: 'http-proxy.conf', dest: '/etc/systemd/system/docker.service.d/http-proxy.conf', when: "{{ docker_use_proxy }}" }
  when: item.when
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  systemd:
    daemon_reload: yes
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users

#- name: Reset ssh connection to allow user changes to affect 'current login user'.
#  meta: reset_connection
#  when: docker_should_reset_ssh == true

# The previous tasks doesn't work so using a work around
# https://github.com/ansible/ansible/issues/27520
- name: Reset ssh connection to allow user changes to affect 'current login user'.
  file:
    path: ~/.ansible/cp
    state: absent
  become: no
  delegate_to: localhost
  changed_when: false
  when: docker_reset_ssh == true

